# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platba',
            name='datum',
        ),
        migrations.AlterField(
            model_name='event',
            name='lektori',
            field=models.ManyToManyField(blank=True, to='nexteria.nextis.Lektor'),
        ),
    ]
