# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextis', '0002_auto_20160119_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyvztah',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_buddy', to='nexteria.nextis.Student'),
        ),
        migrations.AlterField(
            model_name='buddyvztah',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_student', to='nexteria.nextis.Student'),
        ),
    ]
