# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nextis', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='clovek',
        ),
        migrations.RemoveField(
            model_name='student',
            name='datum_nar',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='skola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nextis.Skola'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fakulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nextis.Fakulta'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skolne',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='skolne.Skolne'),
        ),
    ]
