# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextis', '0003_auto_20160119_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='prihlasenie',
            name='event',
        ),
        migrations.RemoveField(
            model_name='prihlasenie',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='buddyvztah',
            options={'verbose_name_plural': '  Buddy Vztahy'},
        ),
        migrations.AlterModelOptions(
            name='clovek',
            options={'verbose_name_plural': '   Ludia'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': '    Eventy'},
        ),
        migrations.AlterModelOptions(
            name='guidevztah',
            options={'verbose_name_plural': '  Guide Vztahy'},
        ),
        migrations.AlterModelOptions(
            name='lektor',
            options={'verbose_name_plural': '   Lektori'},
        ),
        migrations.AlterModelOptions(
            name='novinka',
            options={'verbose_name_plural': '     Novinky'},
        ),
        migrations.AlterModelOptions(
            name='platba',
            options={'verbose_name_plural': ' Platby'},
        ),
        migrations.AlterModelOptions(
            name='skolne',
            options={'verbose_name_plural': ' Skolne'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '   Studenti'},
        ),
        migrations.AlterModelOptions(
            name='vydavok',
            options={'verbose_name_plural': ' Vydavky'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='ucastnici',
        ),
        migrations.AddField(
            model_name='event',
            name='ucastnik',
            field=models.ManyToManyField(blank=True, to='nexteria.nextis.Student'),
        ),
        migrations.DeleteModel(
            name='Prihlasenie',
        ),
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexteria.nextis.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='feedbacky',
            field=models.ManyToManyField(to='nexteria.nextis.Feedback'),
        ),
    ]
