# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextis', '0004_auto_20160120_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ucastnik',
            new_name='ucastnici',
        ),
    ]
