# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextis', '0006_auto_20160120_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('priradene', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='google_mapa',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='clovek',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='skolne',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='skolne',
            name='variabilny_symbol',
            field=models.IntegerField(unique=True),
        ),
    ]
