# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('nextis', '0007_auto_20160417_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=200)),
                ('google_mapa', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stretnutie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaciatok', models.DateTimeField()),
                ('koniec', models.DateTimeField()),
                ('miesto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nexteria.nextis.Miesto')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='google_mapa',
        ),
        migrations.RemoveField(
            model_name='event',
            name='koniec',
        ),
        migrations.RemoveField(
            model_name='event',
            name='miesto',
        ),
        migrations.RemoveField(
            model_name='event',
            name='zaciatok',
        ),
        migrations.AddField(
            model_name='event',
            name='kapacita',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='popis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='typ',
            field=models.CharField(choices=[('ik', 'IK'), ('dbk', 'DBK'), ('for', 'Formalna udalost'), ('ine', 'Ine')], max_length=3),
        ),
        migrations.AlterField(
            model_name='novinka',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AddField(
            model_name='event',
            name='stretnutia',
            field=models.ManyToManyField(blank=True, to='nexteria.nextis.Stretnutie'),
        ),
    ]
