# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('priradene', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Platba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.DateTimeField()),
                ('suma', models.FloatField()),
                ('poznamka', models.CharField(max_length=200)),
                ('ucet', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Platby',
            },
        ),
        migrations.CreateModel(
            name='Skolne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('variabilny_symbol', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Skolne',
            },
        ),
        migrations.CreateModel(
            name='Vydavok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucel', models.CharField(max_length=50)),
                ('suma', models.FloatField()),
                ('splatnost', models.DateField()),
                ('uhradene', models.FloatField()),
                ('vlastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skolne.Skolne')),
            ],
            options={
                'verbose_name_plural': 'Vydavky',
            },
        ),
        migrations.AddField(
            model_name='platba',
            name='vlastnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skolne.Skolne'),
        ),
    ]
