# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 01:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BuddyVztah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaciatok', models.DateField()),
                ('koniec', models.DateField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextis.Buddy')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('pocet_kreditov', models.IntegerField()),
                ('zaciatok', models.DateTimeField()),
                ('koniec', models.DateTimeField()),
                ('miesto', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('0', 'IK'), ('1', 'DBK')], max_length=3)),
                ('popis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fakulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('skratka', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GuideVztah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaciatok', models.DateField()),
                ('koniec', models.DateField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextis.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='Lektor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stav', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 'alumni')], max_length=6)),
                ('zaciatok_rok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Novinka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('vytvorene', models.DateTimeField(auto_now_add=True)),
                ('upravene', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.DateTimeField()),
                ('suma', models.FloatField()),
                ('poznamka', models.CharField(max_length=200)),
                ('ucet', models.CharField(max_length=50)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prihlasenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doodle', models.BooleanField()),
                ('prisiel', models.BooleanField()),
                ('feedback', models.BooleanField()),
                ('poznamka', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextis.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Skola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('mesto', models.CharField(max_length=100)),
                ('skratka', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Skolne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('variabilny_symbol', models.IntegerField()),
                ('platby', models.ManyToManyField(to='nextis.Platba')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_nar', models.DateField()),
                ('rok_zaciatku', models.IntegerField()),
                ('fakulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextis.Fakulta')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextis.Level')),
                ('skolne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nextis.Skolne')),
            ],
        ),
        migrations.CreateModel(
            name='Vydavok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucel', models.CharField(max_length=50)),
                ('suma', models.FloatField()),
                ('splatnost', models.DateField()),
                ('uhradene', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='clovek',
            name='telefon_cislo',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='skolne',
            name='vydavky',
            field=models.ManyToManyField(to='nextis.Vydavok'),
        ),
        migrations.AddField(
            model_name='prihlasenie',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextis.Student'),
        ),
        migrations.AddField(
            model_name='novinka',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextis.Clovek'),
        ),
        migrations.AddField(
            model_name='guidevztah',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextis.Student'),
        ),
        migrations.AddField(
            model_name='guide',
            name='studenti',
            field=models.ManyToManyField(through='nextis.GuideVztah', to='nextis.Student'),
        ),
        migrations.AddField(
            model_name='fakulta',
            name='skola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextis.Skola'),
        ),
        migrations.AddField(
            model_name='event',
            name='lektori',
            field=models.ManyToManyField(to='nextis.Lektor'),
        ),
        migrations.AddField(
            model_name='event',
            name='levely',
            field=models.ManyToManyField(to='nextis.Level'),
        ),
        migrations.AddField(
            model_name='event',
            name='ucastnici',
            field=models.ManyToManyField(through='nextis.Prihlasenie', to='nextis.Student'),
        ),
        migrations.AddField(
            model_name='buddyvztah',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextis.Student'),
        ),
        migrations.AddField(
            model_name='buddy',
            name='studenti',
            field=models.ManyToManyField(through='nextis.BuddyVztah', to='nextis.Student'),
        ),
    ]
